/**
 * Periodic Table Element Data
 * Self-contained element data for chemistry assessments
 * Based on standard periodic table reference materials
 */

export interface Element {
	atomicNumber: number;
	symbol: string;
	name: string;
	atomicMass: number;
	group: number;
	period: number;
	category: string;
	electronConfiguration: string;
	state: string; // solid, liquid, gas
	color: string; // For category color coding
}

export const elements: Element[] = [
	// Period 1
	{
		atomicNumber: 1,
		symbol: "H",
		name: "Hydrogen",
		atomicMass: 1.008,
		group: 1,
		period: 1,
		category: "nonmetal",
		electronConfiguration: "1s¹",
		state: "gas",
		color: "#fef3c7",
	},
	{
		atomicNumber: 2,
		symbol: "He",
		name: "Helium",
		atomicMass: 4.003,
		group: 18,
		period: 1,
		category: "noble gas",
		electronConfiguration: "1s²",
		state: "gas",
		color: "#dbeafe",
	},

	// Period 2
	{
		atomicNumber: 3,
		symbol: "Li",
		name: "Lithium",
		atomicMass: 6.94,
		group: 1,
		period: 2,
		category: "alkali metal",
		electronConfiguration: "[He] 2s¹",
		state: "solid",
		color: "#fecaca",
	},
	{
		atomicNumber: 4,
		symbol: "Be",
		name: "Beryllium",
		atomicMass: 9.012,
		group: 2,
		period: 2,
		category: "alkaline earth",
		electronConfiguration: "[He] 2s²",
		state: "solid",
		color: "#fed7aa",
	},
	{
		atomicNumber: 5,
		symbol: "B",
		name: "Boron",
		atomicMass: 10.81,
		group: 13,
		period: 2,
		category: "metalloid",
		electronConfiguration: "[He] 2s² 2p¹",
		state: "solid",
		color: "#d1fae5",
	},
	{
		atomicNumber: 6,
		symbol: "C",
		name: "Carbon",
		atomicMass: 12.01,
		group: 14,
		period: 2,
		category: "nonmetal",
		electronConfiguration: "[He] 2s² 2p²",
		state: "solid",
		color: "#fef3c7",
	},
	{
		atomicNumber: 7,
		symbol: "N",
		name: "Nitrogen",
		atomicMass: 14.01,
		group: 15,
		period: 2,
		category: "nonmetal",
		electronConfiguration: "[He] 2s² 2p³",
		state: "gas",
		color: "#fef3c7",
	},
	{
		atomicNumber: 8,
		symbol: "O",
		name: "Oxygen",
		atomicMass: 16.0,
		group: 16,
		period: 2,
		category: "nonmetal",
		electronConfiguration: "[He] 2s² 2p⁴",
		state: "gas",
		color: "#fef3c7",
	},
	{
		atomicNumber: 9,
		symbol: "F",
		name: "Fluorine",
		atomicMass: 19.0,
		group: 17,
		period: 2,
		category: "halogen",
		electronConfiguration: "[He] 2s² 2p⁵",
		state: "gas",
		color: "#e9d5ff",
	},
	{
		atomicNumber: 10,
		symbol: "Ne",
		name: "Neon",
		atomicMass: 20.18,
		group: 18,
		period: 2,
		category: "noble gas",
		electronConfiguration: "[He] 2s² 2p⁶",
		state: "gas",
		color: "#dbeafe",
	},

	// Period 3
	{
		atomicNumber: 11,
		symbol: "Na",
		name: "Sodium",
		atomicMass: 22.99,
		group: 1,
		period: 3,
		category: "alkali metal",
		electronConfiguration: "[Ne] 3s¹",
		state: "solid",
		color: "#fecaca",
	},
	{
		atomicNumber: 12,
		symbol: "Mg",
		name: "Magnesium",
		atomicMass: 24.31,
		group: 2,
		period: 3,
		category: "alkaline earth",
		electronConfiguration: "[Ne] 3s²",
		state: "solid",
		color: "#fed7aa",
	},
	{
		atomicNumber: 13,
		symbol: "Al",
		name: "Aluminum",
		atomicMass: 26.98,
		group: 13,
		period: 3,
		category: "metal",
		electronConfiguration: "[Ne] 3s² 3p¹",
		state: "solid",
		color: "#e5e7eb",
	},
	{
		atomicNumber: 14,
		symbol: "Si",
		name: "Silicon",
		atomicMass: 28.09,
		group: 14,
		period: 3,
		category: "metalloid",
		electronConfiguration: "[Ne] 3s² 3p²",
		state: "solid",
		color: "#d1fae5",
	},
	{
		atomicNumber: 15,
		symbol: "P",
		name: "Phosphorus",
		atomicMass: 30.97,
		group: 15,
		period: 3,
		category: "nonmetal",
		electronConfiguration: "[Ne] 3s² 3p³",
		state: "solid",
		color: "#fef3c7",
	},
	{
		atomicNumber: 16,
		symbol: "S",
		name: "Sulfur",
		atomicMass: 32.07,
		group: 16,
		period: 3,
		category: "nonmetal",
		electronConfiguration: "[Ne] 3s² 3p⁴",
		state: "solid",
		color: "#fef3c7",
	},
	{
		atomicNumber: 17,
		symbol: "Cl",
		name: "Chlorine",
		atomicMass: 35.45,
		group: 17,
		period: 3,
		category: "halogen",
		electronConfiguration: "[Ne] 3s² 3p⁵",
		state: "gas",
		color: "#e9d5ff",
	},
	{
		atomicNumber: 18,
		symbol: "Ar",
		name: "Argon",
		atomicMass: 39.95,
		group: 18,
		period: 3,
		category: "noble gas",
		electronConfiguration: "[Ne] 3s² 3p⁶",
		state: "gas",
		color: "#dbeafe",
	},

	// Period 4 - Transition metals included
	{
		atomicNumber: 19,
		symbol: "K",
		name: "Potassium",
		atomicMass: 39.1,
		group: 1,
		period: 4,
		category: "alkali metal",
		electronConfiguration: "[Ar] 4s¹",
		state: "solid",
		color: "#fecaca",
	},
	{
		atomicNumber: 20,
		symbol: "Ca",
		name: "Calcium",
		atomicMass: 40.08,
		group: 2,
		period: 4,
		category: "alkaline earth",
		electronConfiguration: "[Ar] 4s²",
		state: "solid",
		color: "#fed7aa",
	},
	{
		atomicNumber: 21,
		symbol: "Sc",
		name: "Scandium",
		atomicMass: 44.96,
		group: 3,
		period: 4,
		category: "transition metal",
		electronConfiguration: "[Ar] 3d¹ 4s²",
		state: "solid",
		color: "#fecdd3",
	},
	{
		atomicNumber: 22,
		symbol: "Ti",
		name: "Titanium",
		atomicMass: 47.87,
		group: 4,
		period: 4,
		category: "transition metal",
		electronConfiguration: "[Ar] 3d² 4s²",
		state: "solid",
		color: "#fecdd3",
	},
	{
		atomicNumber: 23,
		symbol: "V",
		name: "Vanadium",
		atomicMass: 50.94,
		group: 5,
		period: 4,
		category: "transition metal",
		electronConfiguration: "[Ar] 3d³ 4s²",
		state: "solid",
		color: "#fecdd3",
	},
	{
		atomicNumber: 24,
		symbol: "Cr",
		name: "Chromium",
		atomicMass: 52.0,
		group: 6,
		period: 4,
		category: "transition metal",
		electronConfiguration: "[Ar] 3d⁵ 4s¹",
		state: "solid",
		color: "#fecdd3",
	},
	{
		atomicNumber: 25,
		symbol: "Mn",
		name: "Manganese",
		atomicMass: 54.94,
		group: 7,
		period: 4,
		category: "transition metal",
		electronConfiguration: "[Ar] 3d⁵ 4s²",
		state: "solid",
		color: "#fecdd3",
	},
	{
		atomicNumber: 26,
		symbol: "Fe",
		name: "Iron",
		atomicMass: 55.85,
		group: 8,
		period: 4,
		category: "transition metal",
		electronConfiguration: "[Ar] 3d⁶ 4s²",
		state: "solid",
		color: "#fecdd3",
	},
	{
		atomicNumber: 27,
		symbol: "Co",
		name: "Cobalt",
		atomicMass: 58.93,
		group: 9,
		period: 4,
		category: "transition metal",
		electronConfiguration: "[Ar] 3d⁷ 4s²",
		state: "solid",
		color: "#fecdd3",
	},
	{
		atomicNumber: 28,
		symbol: "Ni",
		name: "Nickel",
		atomicMass: 58.69,
		group: 10,
		period: 4,
		category: "transition metal",
		electronConfiguration: "[Ar] 3d⁸ 4s²",
		state: "solid",
		color: "#fecdd3",
	},
	{
		atomicNumber: 29,
		symbol: "Cu",
		name: "Copper",
		atomicMass: 63.55,
		group: 11,
		period: 4,
		category: "transition metal",
		electronConfiguration: "[Ar] 3d¹⁰ 4s¹",
		state: "solid",
		color: "#fecdd3",
	},
	{
		atomicNumber: 30,
		symbol: "Zn",
		name: "Zinc",
		atomicMass: 65.38,
		group: 12,
		period: 4,
		category: "transition metal",
		electronConfiguration: "[Ar] 3d¹⁰ 4s²",
		state: "solid",
		color: "#fecdd3",
	},
	{
		atomicNumber: 31,
		symbol: "Ga",
		name: "Gallium",
		atomicMass: 69.72,
		group: 13,
		period: 4,
		category: "metal",
		electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p¹",
		state: "solid",
		color: "#e5e7eb",
	},
	{
		atomicNumber: 32,
		symbol: "Ge",
		name: "Germanium",
		atomicMass: 72.63,
		group: 14,
		period: 4,
		category: "metalloid",
		electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p²",
		state: "solid",
		color: "#d1fae5",
	},
	{
		atomicNumber: 33,
		symbol: "As",
		name: "Arsenic",
		atomicMass: 74.92,
		group: 15,
		period: 4,
		category: "metalloid",
		electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p³",
		state: "solid",
		color: "#d1fae5",
	},
	{
		atomicNumber: 34,
		symbol: "Se",
		name: "Selenium",
		atomicMass: 78.97,
		group: 16,
		period: 4,
		category: "nonmetal",
		electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁴",
		state: "solid",
		color: "#fef3c7",
	},
	{
		atomicNumber: 35,
		symbol: "Br",
		name: "Bromine",
		atomicMass: 79.9,
		group: 17,
		period: 4,
		category: "halogen",
		electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁵",
		state: "liquid",
		color: "#e9d5ff",
	},
	{
		atomicNumber: 36,
		symbol: "Kr",
		name: "Krypton",
		atomicMass: 83.8,
		group: 18,
		period: 4,
		category: "noble gas",
		electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁶",
		state: "gas",
		color: "#dbeafe",
	},

	// Period 5 - Key elements (simplified for brevity)
	{
		atomicNumber: 37,
		symbol: "Rb",
		name: "Rubidium",
		atomicMass: 85.47,
		group: 1,
		period: 5,
		category: "alkali metal",
		electronConfiguration: "[Kr] 5s¹",
		state: "solid",
		color: "#fecaca",
	},
	{
		atomicNumber: 38,
		symbol: "Sr",
		name: "Strontium",
		atomicMass: 87.62,
		group: 2,
		period: 5,
		category: "alkaline earth",
		electronConfiguration: "[Kr] 5s²",
		state: "solid",
		color: "#fed7aa",
	},
	{
		atomicNumber: 47,
		symbol: "Ag",
		name: "Silver",
		atomicMass: 107.87,
		group: 11,
		period: 5,
		category: "transition metal",
		electronConfiguration: "[Kr] 4d¹⁰ 5s¹",
		state: "solid",
		color: "#fecdd3",
	},
	{
		atomicNumber: 53,
		symbol: "I",
		name: "Iodine",
		atomicMass: 126.9,
		group: 17,
		period: 5,
		category: "halogen",
		electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p⁵",
		state: "solid",
		color: "#e9d5ff",
	},
	{
		atomicNumber: 54,
		symbol: "Xe",
		name: "Xenon",
		atomicMass: 131.29,
		group: 18,
		period: 5,
		category: "noble gas",
		electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p⁶",
		state: "gas",
		color: "#dbeafe",
	},

	// Period 6 - Key elements
	{
		atomicNumber: 55,
		symbol: "Cs",
		name: "Cesium",
		atomicMass: 132.91,
		group: 1,
		period: 6,
		category: "alkali metal",
		electronConfiguration: "[Xe] 6s¹",
		state: "solid",
		color: "#fecaca",
	},
	{
		atomicNumber: 56,
		symbol: "Ba",
		name: "Barium",
		atomicMass: 137.33,
		group: 2,
		period: 6,
		category: "alkaline earth",
		electronConfiguration: "[Xe] 6s²",
		state: "solid",
		color: "#fed7aa",
	},
	{
		atomicNumber: 79,
		symbol: "Au",
		name: "Gold",
		atomicMass: 196.97,
		group: 11,
		period: 6,
		category: "transition metal",
		electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹",
		state: "solid",
		color: "#fecdd3",
	},
	{
		atomicNumber: 80,
		symbol: "Hg",
		name: "Mercury",
		atomicMass: 200.59,
		group: 12,
		period: 6,
		category: "transition metal",
		electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s²",
		state: "liquid",
		color: "#fecdd3",
	},
	{
		atomicNumber: 82,
		symbol: "Pb",
		name: "Lead",
		atomicMass: 207.2,
		group: 14,
		period: 6,
		category: "metal",
		electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",
		state: "solid",
		color: "#e5e7eb",
	},
	{
		atomicNumber: 86,
		symbol: "Rn",
		name: "Radon",
		atomicMass: 222,
		group: 18,
		period: 6,
		category: "noble gas",
		electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",
		state: "gas",
		color: "#dbeafe",
	},

	// Period 7 - Key elements
	{
		atomicNumber: 87,
		symbol: "Fr",
		name: "Francium",
		atomicMass: 223,
		group: 1,
		period: 7,
		category: "alkali metal",
		electronConfiguration: "[Rn] 7s¹",
		state: "solid",
		color: "#fecaca",
	},
	{
		atomicNumber: 88,
		symbol: "Ra",
		name: "Radium",
		atomicMass: 226,
		group: 2,
		period: 7,
		category: "alkaline earth",
		electronConfiguration: "[Rn] 7s²",
		state: "solid",
		color: "#fed7aa",
	},
];

// Helper to get element by atomic number
export function getElementByNumber(atomicNumber: number): Element | undefined {
	return elements.find((el) => el.atomicNumber === atomicNumber);
}

// Helper to get element by symbol
export function getElementBySymbol(symbol: string): Element | undefined {
	return elements.find((el) => el.symbol === symbol);
}
