/**
 * This contains copies of the data types we use in PIEOneer. These types, unlike
 * the ones in the datastore package, should not have any dependencies, and might in some
 * cases be more shallow than their originals. The main reason for these is that they should
 * be able to be used in front-end code (as well as the PIEOneer backend code).
 *
 * INCLUDING REFERENCES TO THE DATASTORE PACKAGE INSTEAD WILL MAKE PIEONEER THROW 500
 * EVERYWHERE WITHOUT ANY FURTHER EXPLANATION
 */
import type {
	FormativeDeliveryPolicy,
	FormativeItemPolicy,
	FormativeSectionSlice,
} from "../formative/types.js";
import type {
	TimedMediaSectionData,
	TimedMediaSectionSessionSlice,
} from "../timed-media/types.js";

export type { FormativeDeliveryPolicy, FormativeItemPolicy };
export type { TimedMediaSectionData };

export interface BaseEntity {
	id?: string;
	createdAt?: Date;
	updatedAt?: Date;
}

export interface SemVerPrerelease {
	tag: string;
	version: number;
}

export interface SemVer {
	major: number;
	minor: number;
	patch: number;
	prerelease?: SemVerPrerelease;
}

export interface VersionEntity extends BaseEntity {
	baseId: string;
	signature?: string;
	version: SemVer;
}

export interface SearchMetaData {
	[key: string]: any;
}

export interface SearchMetaDataEntity extends BaseEntity {
	searchMetaData?: SearchMetaData;
}

export interface ConfigElements {
	[key: string]: string;
}

export interface PieModel {
	id: string;
	element: string;
	/**
	 * QTI/APIP-style accessibility catalogs owned by this model's renderable fields
	 * (prompt, choices, feedback, rationale, etc.).
	 */
	accessibilityCatalogs?: AccessibilityCatalog[];

	[key: string]: any;
}

export interface ConfigEntity {
	id?: string;
	markup: string;
	elements: ConfigElements;
	models: PieModel[];
	configuration?: Record<string, any>; // NEW: Configure settings for authoring mode

	/**
	 * QTI 3.0: Extracted accessibility catalogs from embedded SSML.
	 * Automatically generated by SSMLExtractor when <speak> tags are found in content.
	 */
	extractedCatalogs?: AccessibilityCatalog[];

	[key: string]: any;
}

export interface ConfigContainerEntity extends BaseEntity {
	config: ConfigEntity;
}

export interface PassageEntity
	extends VersionEntity,
		ConfigContainerEntity,
		SearchMetaDataEntity {
	name: string;
	/** QTI/APIP-style accessibility catalogs owned by this passage content. */
	accessibilityCatalogs?: AccessibilityCatalog[];
	retired?: boolean;
	published?: boolean;
	// Search result highlights from OpenSearch (keyed by field name)
	highlights?: Record<string, string[]>;
}

export interface ItemEntity
	extends VersionEntity,
		ConfigContainerEntity,
		SearchMetaDataEntity {
	name?: string;
	/**
	 * `null` as well as absent, because importers write it. JSON has no
	 * `undefined`, so an item transformed from another format carries an explicit
	 * `passage: null` for "no passage" — the runtime has always tested for
	 * null, so it expected it while the type denied it. Excluding null
	 * only meant a host feeding real importer output through a typed path had to
	 * cast it away.
	 */
	passage?: string | PassageEntity | null;
	/** QTI/APIP-style accessibility catalogs owned by the item root. */
	accessibilityCatalogs?: AccessibilityCatalog[];
	retired?: boolean;
	published?: boolean;
	configuration?: any;
	// Search result highlights from OpenSearch (keyed by field name)
	highlights?: Record<string, string[]>;
}

/**
 * `baseId` and `version` are optional on an entity a section references. They
 * identify a stored version, which a host building a section from an item
 * config does not have, and no player reads either.
 */
type WithOptionalVersion<T extends VersionEntity> = Omit<
	T,
	"baseId" | "version"
> &
	Partial<Pick<VersionEntity, "baseId" | "version">>;

/**
 * A passage as a section's item references it. `name` is optional on the same
 * ground: the section player reads it only as a fallback for a missing `id`.
 */
export type ReferencedPassageEntity = Omit<
	WithOptionalVersion<PassageEntity>,
	"name"
> & {
	name?: string;
};

/** An item as `AssessmentItemRef.item` references it. */
export type ReferencedItemEntity = Omit<
	WithOptionalVersion<ItemEntity>,
	"passage"
> & {
	passage?: string | ReferencedPassageEntity | null;
};

/**
 * Metadata specifically for interpretation by clients, typically containing
 * options that are relevant for the user interface. This is not indexed for search.
 */
export interface SettingsMetaData {
	[key: string]: any;
}

/**
 * Objects that contain metadata in the settings property, which is NOT indexed for search
 * but typically only relevant for particular client cases.
 */
export interface SettingsMetaDataEntity {
	settings?: SettingsMetaData;
}

// ============================================================================
// QTI-aligned assessment model (QTI 2.x compatible shape)
// ============================================================================

export type RubricBlockView =
	| "author"
	| "candidate"
	| "proctor"
	| "scorer"
	| "testConstructor"
	| "tutor";

export interface RubricBlock {
	identifier?: string;
	/** QTI spec: space-separated list of roles; stored as an array */
	view: RubricBlockView[];
	class?: "stimulus" | "instructions" | "rubric";

	/**
	 * Versioned ID reference to the passage (when class="stimulus").
	 */
	passageVId?: string;

	/**
	 * Embedded passage entity (PIE-native approach).
	 * The passage is rendered using the same ItemPlayer infrastructure as items.
	 * Contains a PIE config with markup, elements, and models.
	 */
	passage?: PassageEntity;

	/**
	 * Simple HTML content string (for basic use cases).
	 * Alternative to the passage entity approach.
	 */
	content?: string;
}

/**
 * QTI-aligned assessment item reference (maps to qti-assessment-item-ref).
 * References an item within a section. The item property contains the resolved
 * ItemEntity with its PIE config.
 */
export interface AssessmentItemRef extends SearchMetaDataEntity {
	id?: string;
	identifier: string;
	title?: string;
	required?: boolean;

	/**
	 * Item virtual ID - stable identifier for the item across versions
	 */
	itemVId?: string;

	/**
	 * Resolved item entity with PIE config.
	 * This is populated by the client before passing to the player.
	 */
	item?: ReferencedItemEntity;

	/** Item-level settings for tool requirements and customization */
	settings?: ItemSettings;

	/**
	 * Formative delivery override for this item. Every field overrides the
	 * section's `formative` policy independently, which is the order QTI 3 uses
	 * for `qti-item-session-control` on an item ref versus its section.
	 *
	 * See `docs/prds/formative-delivery-contract.md`.
	 */
	formative?: FormativeItemPolicy;
}

export interface AssessmentSection
	extends SearchMetaDataEntity,
		SettingsMetaDataEntity {
	id?: string;
	identifier: string;
	title?: string;
	visible?: boolean;
	required?: boolean;
	/**
	 * QTI 3 pagination hint (`qti-assessment-section@keep-together`).
	 *
	 * Indicates that the delivery system SHOULD render this section's items
	 * together rather than splitting them across pages. This is strictly a
	 * rendering/layout hint — it does NOT disable item-level navigation,
	 * current-item tracking, or `item-selected` events in the section player.
	 * Paginated and keep-together sections both support Next/Back,
	 * `getCurrentItem()`, and `item-selected` events.
	 */
	keepTogether?: boolean;

	sections?: AssessmentSection[];

	/**
	 * QTI 3.0: Assessment item references (items in this section).
	 * Maps to qti-assessment-item-ref in QTI 3.0 XML.
	 */
	assessmentItemRefs?: AssessmentItemRef[];

	// Shared context (passages/instructions/rubrics) for this section
	rubricBlocks?: RubricBlock[];

	/**
	 * Formative delivery policy for this section: how many Tries a learner gets
	 * on each item, when feedback is revealed, and whether the behavior is on at
	 * all. Absent or `enabled: false` delivers exactly as a section without this
	 * field — no control, no state, no env override.
	 *
	 * Individual items override it through `AssessmentItemRef.formative`. See
	 * `docs/prds/formative-delivery-contract.md`.
	 */
	formative?: FormativeDeliveryPolicy;

	/**
	 * The section flavor. Absent for every section authored so far, and the only
	 * value is `"timed-media"`, which pairs with `timedMedia` below.
	 *
	 * A discriminator on data, not a renderer selector: the host still picks the
	 * layout tag, as every integration that renders a section already does. See
	 * `docs/prds/timed-media-section-contract.md#delivery-attachment`.
	 */
	sectionType?: "timed-media";

	/**
	 * Cue timeline and playback policy for a timed-media section. Carries no media
	 * payload — `stimulusRef` names the `class: "stimulus"` rubric block whose
	 * passage supplies the time source, so the media keeps a Catalog Owner and its
	 * captions, transcript and signed alternates resolve through the
	 * accessibility-catalog rail.
	 *
	 * Ignored unless `sectionType` is `"timed-media"`.
	 */
	timedMedia?: TimedMediaSectionData;

	sort?: string;
}

export interface TestPart {
	id?: string;
	identifier: string;
	navigationMode: "linear" | "nonlinear";
	submissionMode: "individual" | "simultaneous";
	sections: AssessmentSection[];
}

// ============================================================================
// Section and assessment session state
// ============================================================================

/**
 * The host-facing persistence snapshot for one section, returned by
 * `SectionControllerHandle.getSession()` and accepted by `applySession()`.
 *
 * Canonical here rather than in a player or the toolkit: the toolkit is
 * complementary to a player rather than an alternative to one and sits beneath
 * both entry paths, so a shape both need belongs alongside `AssessmentSection`.
 * The delivery slices it carries are defined in this package too, which is what
 * previously forced them to reference this shape in prose instead of types.
 */
export interface SectionControllerSessionState {
	currentItemIndex?: number;
	visitedItemIdentifiers?: string[];
	itemSessions: Record<string, unknown>;
	/**
	 * Formative delivery state — Try counts and reveal state per item.
	 *
	 * Optional, and its absence is indistinguishable from a snapshot saved
	 * before formative delivery existed, which is what keeps existing persisted
	 * sessions valid. A slice with an unrecognized `version` is rejected whole
	 * and formative state starts clean; `itemSessions` in the same snapshot is
	 * unaffected, so a formative version bump never costs a learner responses.
	 */
	formative?: FormativeSectionSlice;
	/**
	 * Timed-media delivery state — media progress, cue visits and completions.
	 *
	 * Same posture as `formative`: optional, absence indistinguishable from a
	 * pre-timed-media snapshot, and an unrecognized `version` rejected whole so
	 * cue progress restarts while item sessions in the same snapshot are applied
	 * untouched.
	 */
	timedMedia?: TimedMediaSectionSessionSlice;
}

export interface AssessmentSessionNavigationState {
	currentSectionIndex: number;
	visitedSectionIdentifiers: string[];
	currentSectionIdentifier?: string;
}

export interface AssessmentSessionRealization {
	seed: string;
	sectionIdentifiers: string[];
}

export interface AssessmentSectionSessionState {
	sectionIdentifier: string;
	updatedAt: string;
	/**
	 * The full section snapshot. Typing this as anything narrower drops the
	 * delivery slices without a compiler error at the point of loss.
	 */
	session: SectionControllerSessionState | null;
}

export interface AssessmentSession {
	version: 1;
	assessmentAttemptSessionIdentifier: string;
	assessmentId: string;
	startedAt: string;
	updatedAt: string;
	completedAt?: string;
	navigationState: AssessmentSessionNavigationState;
	realization: AssessmentSessionRealization;
	sectionSessions: Record<string, AssessmentSectionSessionState>;
	contextVariables?: Record<string, unknown>;
}

// ============================================================================
// QTI 3.0 Types
// ============================================================================

export interface ContextDeclaration {
	identifier: string;
	baseType:
		| "boolean"
		| "integer"
		| "float"
		| "string"
		| "identifier"
		| "point"
		| "pair"
		| "directedPair"
		| "duration"
		| "file"
		| "uri";
	cardinality: "single" | "multiple" | "ordered" | "record";
	defaultValue?: any;
}

// ----------------------------------------------------------------------------
// Media asset references
// ----------------------------------------------------------------------------

export type MediaKind = "image" | "audio" | "video" | "other";

export interface MediaSource {
	src: string;
	type?: string;
	width?: number;
	height?: number;
	bitrate?: number;
}

export interface TextTrackRef {
	src: string;
	kind: "captions" | "subtitles" | "descriptions" | "chapters" | "metadata";
	lang: string;
	label: string;
	default?: boolean;
}

export interface TranscriptRef {
	src?: string;
	html?: string;
	plainText?: string;
	lang?: string;
}

/**
 * A referenced media asset and its accessible alternates.
 *
 * Deliberately one vocabulary for every media consumer (accessibility catalog
 * cards today, stimulus media later) rather than per-consumer media fields.
 * Which fields are *required* is resolved per consumer instead of by making
 * everything optional at the type level — a type where nothing is required
 * stops catching anything. For a sign-language card, `sources` carries the
 * signing recording, `poster`/`durationSeconds` are not applicable, and
 * `tracks`/`transcript` are meaningless (captions on a signing video would be
 * the English text already on screen).
 */
export interface MediaAssetRef {
	version: 1;
	id: string;
	kind: MediaKind;
	sources: MediaSource[];
	poster?: string;
	thumbnail?: string;
	durationSeconds?: number;
	tracks?: TextTrackRef[];
	transcript?: TranscriptRef;
	label?: string;
	description?: string;
	lang?: string;
}

/**
 * Time slice of a longer recording, so one file can serve several content
 * nodes. Mirrors QTI 3's Media Fragments URI usage, which replaced APIP's
 * separate start/end cue elements.
 */
export interface MediaFragmentRange {
	startSeconds: number;
	endSeconds?: number;
}

/**
 * Payload for a `sign-language` catalog card.
 *
 * A signing video cannot be expressed as a string, so it does not use the
 * card's `content` field at all. This payload carries what QTI 3 expresses
 * inside `qti-card-entry` — multiple sources, MIME types, poster, and an
 * optional time range.
 *
 * Note there is no `kind` discriminant: the card's `catalog` field is QTI's
 * `qti-card@support` and is the only discriminator. Restating it here would
 * create a second source of truth that can disagree with the first.
 */
export interface SignLanguageCardPayload {
	/**
	 * ISO 639-3 sign language code of the *adaptation*, not of the item's base
	 * content (AfA/PNP's `languageOfAdaptation` distinction). A Spanish item's
	 * signed alternate is LSM, not ASL, so this must never be inferred from the
	 * item or assessment content language.
	 *
	 * Optional, and redundant when it equals the card's `language`. The card's
	 * `language` is QTI's `xml:lang` on the card entry and is the only field
	 * catalog resolution selects on — it decides *which* card is returned, before
	 * anything knows the card is a signing card. This one is read after
	 * resolution, to name the language in the region's accessible label and to
	 * refuse a card in a sign language the learner did not ask for. Author it only
	 * where the two genuinely differ, which is a card tagged with the item's
	 * content language (`language: "en-US"`, `signLang: "ase"`) so that resolution
	 * reaches it by the default-language rung.
	 */
	signLang?: string;
	media: MediaAssetRef;
	fragment?: MediaFragmentRange;
}

/**
 * Payload for a `spoken` catalog card that is a recording rather than a script.
 *
 * QTI 3 treats recorded audio and synthesized speech as the *same* support:
 * both are `spoken`, and a card holds recorded audio through `qti-file-href`
 * plus a MIME type. So this is not a new accommodation, it is the other form the
 * existing one can take.
 *
 * A node commonly carries both this and a `content` card in the same language —
 * APIP's pattern, which QTI's migration guidance keeps, because the script is
 * both what the audio was generated from and the fallback for when the audio
 * cannot play. Resolution picks between them with `CatalogLookupOptions.form`.
 *
 * No `kind` discriminant, for the same reason `SignLanguageCardPayload` has
 * none: the card's `catalog` already says what this is.
 */
export interface SpokenAudioCardPayload {
	media: MediaAssetRef;
	fragment?: MediaFragmentRange;
}

/**
 * Structured payloads a catalog card may carry instead of a `content` string.
 *
 * Which member applies is decided by the card's `catalog`, not by a field
 * inside the payload, so this union carries no discriminant. Consumers select a
 * card by catalog type and then validate the payload structurally — which they
 * must do regardless, since catalog data is authored, wire-facing, and
 * untrusted.
 */
export type CatalogCardPayload =
	| SignLanguageCardPayload
	| SpokenAudioCardPayload;

/**
 * One alternate representation of a content node, keyed to it by
 * `data-catalog-idref`.
 *
 * Maps onto QTI 3's `qti-card`: `catalog` is `@support`, `language` is the card
 * entry's `xml:lang`, and QTI's single content slot is represented by exactly
 * one of `content` or `payload`.
 *
 * One generic `payload` slot, not a field per accommodation. This is the shape
 * `pie-elements-ng` (PIE-879) and the `pie-api-aws` Learnosity importer
 * (PIE-881) restate structurally; all three read the same authored JSON and none
 * of them takes a package dependency on the others, so keeping the declarations
 * identical is the only thing holding interop together. It briefly was not:
 * those two producers wrote the signing payload under `signLanguage`, this
 * repo tolerated that as an input alias, and the alias was folded in on the
 * resolution path but not the enumeration path — so an imported card rendered
 * its signing video and simultaneously reported that the item had no signed
 * alternate. Both producers now emit `payload` and the alias is gone.
 */
export interface CatalogCard {
	catalog: string; // 'spoken', 'sign-language', 'braille', etc.
	language?: string;
	/**
	 * Optional presentation policy carried by catalog-backed UI such as an audio
	 * transcript. Unknown values remain authored metadata for the capability that
	 * understands them; the generic catalog resolver does not reinterpret them.
	 */
	visibility?: string;
	/**
	 * The string form of the card's content, for catalog types a string can
	 * express: SSML for `spoken`, plain text for `simplified-language`, and so
	 * on. Absent on cards that carry a structured `payload` instead — nothing
	 * is projected or mirrored into it, so there is never a second copy of the
	 * payload's data to fall out of sync.
	 */
	content?: string;
	/**
	 * The structured form, for catalog types a string cannot express. Interpreted
	 * according to `catalog`.
	 */
	payload?: CatalogCardPayload;
}

export interface AccessibilityCatalog {
	identifier: string;
	cards: CatalogCard[];
}

export interface PersonalNeedsProfile {
	supports: string[];
	prohibitedSupports?: string[];
}

/**
 * QTI 3.0: Reference to a shared stimulus (passage).
 * Maps to qti-assessment-stimulus-ref element.
 *
 * NOTE: Not currently used. We embed PassageEntity directly in RubricBlock instead.
 * Kept for potential future use if we need to support external stimulus references.
 */
/*
export interface StimulusRef {
	identifier: string;
	href: string;
}
*/

export interface AssessmentEntity extends BaseEntity, SearchMetaDataEntity {
	name?: string;
	title?: string;
	identifier?: string;
	description?: string;

	/** Enhanced structured settings for assessment configuration */
	settings?: AssessmentSettings;

	/** QTI version - '3.0' for QTI 3.0 format */
	qtiVersion?: "3.0";

	/** QTI 3.0: Context declarations (global shared variables) */
	contextDeclarations?: ContextDeclaration[];

	/** QTI 3.0: Integrated APIP accessibility catalogs */
	accessibilityCatalogs?: AccessibilityCatalog[];

	/** QTI 3.0: Personal Needs Profile (PNP 3.0) */
	personalNeedsProfile?: PersonalNeedsProfile;

	/**
	 * QTI 3.0: testParts structure (authoritative for QTI format).
	 */
	testParts?: TestPart[];

	/** QTI 3.0: Stimulus material references (Phase 3 - placeholder) */
	stimulusRefs?: any[];
}

/**
 * Enhanced settings structure for assessment configuration.
 * Provides structured fields for district policies, test administration,
 * tool configurations, and theme settings while remaining extensible.
 */
export interface AssessmentSettings {
	/** District/organization policies */
	districtPolicy?: {
		blockedTools?: string[]; // PNP support IDs that are blocked
		requiredTools?: string[]; // PNP support IDs that are required
	};

	/** Test administration configuration */
	testAdministration?: {
		/**
		 * Per-session override by tool id: `true` grants the tool, `false`
		 * withdraws it. Outranks every policy level except a district block.
		 */
		toolOverrides?: Record<string, boolean>;
	};

	/** Tool-specific provider configurations */
	toolConfigs?: {
		// Calculator-specific options are owned by the calculator tool package.
		calculator?: AssessmentCalculatorConfig;
		/**
		 * Text-to-speech configuration.
		 *
		 * Standard parameters (voice, rate, pitch) are portable across providers
		 * and follow W3C Web Speech API specifications.
		 *
		 * Provider-specific extensions should be placed in providerOptions.
		 *
		 * @see https://w3c.github.io/speech-api/
		 */
		textToSpeech?: {
			/**
			 * TTS provider
			 *
			 * @standard "browser" uses W3C Web Speech API
			 * @extension "polly" and "custom" are provider-specific
			 */
			provider?: "browser" | "polly" | "custom";

			/**
			 * Voice identifier (provider-specific names)
			 *
			 * @standard W3C Web Speech API (concept)
			 * @example "Joanna" (Polly), "en-US-Standard-A" (Google), browser voices
			 */
			voice?: string;

			/**
			 * Speech rate (speed multiplier)
			 *
			 * @standard W3C Web Speech API
			 * @range 0.25 to 4.0
			 * @default 1.0
			 */
			rate?: number;

			/**
			 * Pitch adjustment
			 *
			 * @standard W3C Web Speech API
			 * @range 0 to 2 (as multiplier)
			 * @default 1.0
			 */
			pitch?: number;

			/**
			 * Speech Rule Engine options for generated MathML speech.
			 *
			 * `style` is passed to SRE directly; ClearSpeak combines multiple
			 * preferences with ":" (for example,
			 * "ImpliedTimes_MoreImpliedTimes:Paren_Silent").
			 *
			 * Mirrors assessment-toolkit's SREMathSpeechOptions without importing
			 * toolkit service types into the shared content contract package.
			 */
			mathSpeech?: {
				domain?: string;
				style?: string;
				engineOptions?: Record<string, unknown>;
			};

			/**
			 * Provider-specific options (extensions)
			 *
			 * @extension Not portable across providers
			 * @example For AWS Polly: { engine: "neural", region: "us-east-1" }
			 * @example For Google Cloud: { audioEncoding: "MP3", effectsProfileId: ["headphone-class-device"] }
			 */
			providerOptions?: Record<string, any>;
		};
		[toolId: string]: any; // Other tool configs
	};

	/** Product-specific extensions */
	[key: string]: any;
}

/**
 * Calculator options exposed through assessment settings.
 * The engine is implicit (Desmos).
 */
export interface AssessmentCalculatorConfig {
	type?: "basic" | "scientific" | "graphing";
	[key: string]: any;
}

/**
 * Item-level settings for tool requirements.
 * Used in AssessmentItemRef.settings to specify item-specific tool needs.
 */
export interface ItemSettings {
	requiredTools?: string[]; // PNP support IDs required for this item
	restrictedTools?: string[]; // PNP support IDs blocked for this item
	toolParameters?: Record<string, any>; // Tool-specific config per item

	[key: string]: any; // Product extensions
}

export type PlayerMode = "gather" | "view" | "evaluate" | "author";

export type PlayerRole = "student" | "instructor";

export interface Env {
	mode: PlayerMode;
	role: PlayerRole;
	partialScoring?: boolean;
}

/** The `detail` of the `player-error` event `pie-item-player` dispatches. */
export interface PieItemPlayerErrorDetail {
	/** The failure, e.g. `ITEM_PLAYER_LOAD_ERROR` or `PIE_CONTROLLER_RUNTIME_ERROR`. */
	code: string;
	message: string;
	/**
	 * True when the item stays usable: a failed update leaves it as it was, and
	 * a failed controller falls back to the authored model. False when the
	 * player has no item to show.
	 */
	recoverable: boolean;
	/** On a load error, the loading step that failed, and the strategy and mode it loaded under. */
	stage?: string;
	strategy?: string;
	mode?: string;
	cause?: unknown;
	/** On a controller error, the element's tag and id, and what the controller looked like. */
	elementName?: string;
	elementId?: string;
	controllerShape?: string;
}

export interface OutcomeResponse {
	id: string;
	element: string;
	score?: number;
	empty?: boolean;
	completed?: boolean;

	[key: string]: any;
}

/**
 * Persists `properties` into the stored session `id` of element `element`. The
 * player passes it to `model()`, as `PieUpdateSession` in
 * `@pie-element/shared-types` declares.
 */
export type PieUpdateSession = (
	id: string,
	element: string,
	properties: Record<string, unknown>,
) => Promise<void>;

export interface PieController {
	model(
		model: PieModel,
		sessionData: any[],
		env?: any,
		updateSession?: PieUpdateSession,
	): Promise<PieModel>;

	outcome(
		modelOrSessionData: PieModel | any[],
		sessionOrEnv?: any,
		env?: any,
	): Promise<OutcomeResponse>;

	score: (config: object, session: object, env: object) => Promise<object>;
	createCorrectResponseSession: (
		config: object,
		env: object,
	) => Promise<object>;
	validate: (model: object, config: object) => any;
}

export interface PieItemElement {
	[elementName: string]: string;
}

export type BundleInfo = {
	url: string;
	hash: string;
};

export type ItemSession = {
	id: string;
	data: any[];
};

export interface PieDefaultModel {
	// supports 'excess' properties as may be defined in pie models
	// https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#strict-object-literal-assignment-checking
	[x: string]: any;
}

export interface PieContent {
	id: string;
	/**
	 * Set of elements to include in the pie, provided in the format `{'element-name': 'mpm-package-name'}`
	 */
	elements: PieItemElement;

	/** Models for each PIE included in the item */
	models: PieModel[];

	markup: string;

	bundle?: BundleInfo;

	resources?: ConfigResource;

	defaultExtraModels?: {
		[key: string]: PieDefaultModel;
	};
}

export interface ConfigResource {
	stylesheets?: {
		url: string;
	}[];
	containerClass?: string;
	passageContainerClass?: string;
}

export interface AdvancedItemConfig {
	id: string;
	pie: PieContent;
	passage?: PieContent;
	instructorResources?: [PieContent];
	defaultExtraModels?: {
		[key: string]: PieDefaultModel;
	};
}

export type ItemConfig = PieContent | AdvancedItemConfig;

/**
 * During the loading of elements from PIE bundles, we do a trick where we make
 * editor components available as web components by appending this to the element name.
 */
export const editorPostFix = "-pie-editor--";

export type ModelUpdatedDetail = {
	update: any;
	reset: boolean;
};

export class ModelUpdatedEvent extends CustomEvent<ModelUpdatedDetail> {
	static TYPE = "model.updated";

	constructor(
		readonly update: any,
		readonly reset: boolean = false,
	) {
		super(ModelUpdatedEvent.TYPE, { bubbles: true, detail: { update, reset } });
	}
}

export type DeleteDone = (e?: Error) => void;

export type DeleteImageDetail = {
	src: string;
	done: DeleteDone;
};

export class DeleteImageEvent extends CustomEvent<DeleteImageDetail> {
	static TYPE = "delete.image";

	constructor(
		readonly src: string,
		readonly done: DeleteDone,
	) {
		super(DeleteImageEvent.TYPE, { bubbles: true, detail: { src, done } });
	}
}

export interface ImageHandler {
	isPasted?: boolean;
	cancel: () => void;
	done: (err?: Error, src?: string) => void;
	fileChosen: (file: File) => void;
	progress: (percent: number, bytes: number, total: number) => void;
}

export class InsertImageEvent extends CustomEvent<ImageHandler> {
	static TYPE = "insert.image";

	constructor(readonly handler: ImageHandler) {
		super(InsertImageEvent.TYPE, { bubbles: true, detail: handler });
	}
}

export type DeleteSoundDetail = {
	src: string;
	done: DeleteDone;
};

export class DeleteSoundEvent extends CustomEvent<DeleteSoundDetail> {
	static TYPE = "delete.sound";

	constructor(
		readonly src: string,
		readonly done: DeleteDone,
	) {
		super(DeleteSoundEvent.TYPE, { bubbles: true, detail: { src, done } });
	}
}

export interface SoundHandler {
	cancel: () => void;
	done: (err?: Error, src?: string) => void;
	fileChosen: File;
	progress: (percent: number, bytes: number, total: number) => void;
}

export class InsertSoundEvent extends CustomEvent<SoundHandler> {
	static TYPE = "insert.sound";

	constructor(readonly handler: SoundHandler) {
		super(InsertSoundEvent.TYPE, { bubbles: true, detail: handler });
	}
}

export interface PieElement extends HTMLElement {
	model: PieModel;
	configuration: any;
	session: any[];
}
