import {
	assertCanonicalThemeDefinitions,
	getBaseThemeVariables,
	listBuiltInColorSchemeDefinitions,
} from "./theme-definitions.js";
import type { ThemeVariables } from "./theme-types.js";

const GENERATED_HEADER =
	"/* Generated by @pie-players/pie-theme. Run `bun run generate:css`; do not edit. */";

function renderDeclarations(variables: Readonly<ThemeVariables>): string {
	return Object.entries(variables)
		.sort(([left], [right]) => (left < right ? -1 : left > right ? 1 : 0))
		.map(([token, value]) => `\t${token}: ${value};`)
		.join("\n");
}

function renderRule(
	selectors: readonly string[],
	variables: Readonly<ThemeVariables>,
): string {
	return `${selectors.join(",\n")} {\n${renderDeclarations(variables)}\n}`;
}

function renderTokensCss(): string {
	return `${GENERATED_HEADER}\n\n${renderRule(
		[":root", '[data-theme="light"]', ':where(pie-theme[theme="light"])'],
		getBaseThemeVariables("light"),
	)}\n\n${renderRule(
		['[data-theme="dark"]', ':where(pie-theme[theme="dark"])'],
		getBaseThemeVariables("dark"),
	)}\n`;
}

function renderColorSchemesCss(): string {
	const rules = listBuiltInColorSchemeDefinitions().map((scheme) =>
		renderRule([`[data-color-scheme="${scheme.id}"]`], scheme.variables),
	);
	return `${GENERATED_HEADER}\n\n${rules.join("\n\n")}\n`;
}

/** Package-internal pure renderer for the two checked-in CSS adapters. */
export function renderPieThemeCss(): Readonly<{
	tokensCss: string;
	colorSchemesCss: string;
}> {
	assertCanonicalThemeDefinitions();
	return Object.freeze({
		tokensCss: renderTokensCss(),
		colorSchemesCss: renderColorSchemesCss(),
	});
}
