#!/usr/bin/env bun
/**
 * The exported names of every public entry of every published package, as
 * committed reports under `api-report/`.
 *
 * `--write` regenerates the reports; the default checks them and fails when an
 * entry's exports changed without a regenerated report, so a surface change is
 * a reviewed diff in the report as well as in the code. Names only: a renamed
 * parameter or a widened type is not visible here.
 *
 * An entry is a package `exports` key with a `dist` target. Its source is the
 * file the build compiles, from `workspaceExports`, and its names are read from
 * that source with `scripts/lib/api-exports.mjs`.
 */

import {
	existsSync,
	mkdirSync,
	readdirSync,
	readFileSync,
	rmSync,
	writeFileSync,
} from "node:fs";
import path from "node:path";
import {
	REPO_ROOT,
	workspaceExports,
	workspacePackages,
} from "../test-support/workspace-sources.ts";
import { formatModuleExports, moduleExports } from "./lib/api-exports.mjs";

const REPORT_DIR = path.join(REPO_ROOT, "api-report");
const HEADER =
	"# Exported names per entry, generated by scripts/api-report.mjs.\n# Regenerate with `bun run api-report`.\n";

const reportFileName = (packageName) =>
	`${packageName.replace(/^@pie-players\//, "")}.api.txt`;

/** Report file name -> report text, for every published package with exports. */
export function renderReports(root = REPO_ROOT) {
	const exportsList = workspaceExports(root);
	const sources = new Map(
		exportsList.map(({ specifier, source }) => [specifier, source]),
	);
	const resolvePackage = (specifier) => sources.get(specifier);
	const reports = new Map();
	for (const { name, manifest } of workspacePackages(root)) {
		if (manifest.private === true) continue;
		const entries = exportsList
			.filter(
				({ specifier, target }) =>
					target &&
					(specifier === name || specifier.startsWith(`${name}/`)),
			)
			.map(({ specifier, source }) => ({
				subpath:
					specifier === name ? "." : `./${specifier.slice(name.length + 1)}`,
				source,
			}))
			.sort((a, b) => (a.subpath < b.subpath ? -1 : a.subpath > b.subpath ? 1 : 0));
		if (entries.length === 0) continue;
		const sections = entries.map(({ subpath, source }) => {
			const lines = formatModuleExports(
				moduleExports(source, { resolvePackage }),
			);
			const body =
				lines.length > 0
					? lines.map((line) => `  ${line}`).join("\n")
					: "  (no named exports)";
			return `${subpath}\n${body}\n`;
		});
		reports.set(
			reportFileName(name),
			`${HEADER}\n${name}\n\n${sections.join("\n")}`,
		);
	}
	return reports;
}

/** Entry -> names, parsed back from a report, for a readable failure. */
function parseReport(text) {
	const entries = new Map();
	let current;
	for (const line of text.split("\n")) {
		if (line.startsWith("  ")) {
			current?.add(line.slice(2));
		} else if (line.startsWith(".")) {
			current = new Set();
			entries.set(line, current);
		}
	}
	return entries;
}

function describeDrift(file, committed, generated) {
	if (committed === undefined) return [`${file}: no committed report`];
	if (generated === undefined) return [`${file}: package no longer published`];
	const before = parseReport(committed);
	const after = parseReport(generated);
	const lines = [];
	for (const entry of new Set([...before.keys(), ...after.keys()])) {
		const was = before.get(entry) ?? new Set();
		const now = after.get(entry) ?? new Set();
		const added = [...now].filter((name) => !was.has(name));
		const removed = [...was].filter((name) => !now.has(name));
		for (const name of added) lines.push(`${file} ${entry}: + ${name}`);
		for (const name of removed) lines.push(`${file} ${entry}: - ${name}`);
	}
	return lines.length > 0 ? lines : [`${file}: formatting differs`];
}

function main() {
	const write = process.argv.includes("--write");
	const generated = renderReports();
	const committed = new Map(
		existsSync(REPORT_DIR)
			? readdirSync(REPORT_DIR)
					.filter((file) => file.endsWith(".api.txt"))
					.map((file) => [
						file,
						readFileSync(path.join(REPORT_DIR, file), "utf8"),
					])
			: [],
	);
	const files = new Set([...generated.keys(), ...committed.keys()]);
	const stale = [...files]
		.sort()
		.filter((file) => generated.get(file) !== committed.get(file));

	if (write) {
		mkdirSync(REPORT_DIR, { recursive: true });
		for (const file of stale) {
			const text = generated.get(file);
			if (text === undefined) rmSync(path.join(REPORT_DIR, file));
			else writeFileSync(path.join(REPORT_DIR, file), text);
			console.log(`[api-report] ${text === undefined ? "removed" : "wrote"} api-report/${file}`);
		}
		return;
	}

	if (stale.length === 0) {
		console.log(`[api-report] ${generated.size} reports current.`);
		return;
	}
	console.error(
		"[api-report] exports changed without a regenerated report. Review the change, then run `bun run api-report` and commit api-report/:",
	);
	for (const file of stale) {
		for (const line of describeDrift(
			file,
			committed.get(file),
			generated.get(file),
		)) {
			console.error(`  ${line}`);
		}
	}
	process.exitCode = 1;
}

if (import.meta.main) main();
