/**
 * Tool Policy Engine — facade class (M8 — see
 * `.cursor/plans/m8-design.md` § 2).
 *
 * Wraps `composeDecision(...)` with engine-instance state:
 *   - bound inputs (`tools`, `assessment`, `currentItemRef`, ...)
 *   - registered custom `PolicySource`s
 *   - `onPolicyChange` subscriber bus
 *   - `dispose()` clean-up
 *
 * The class has no DOM dependency and no Svelte runes. It is safe to
 * instantiate inside a worker, in a Node test, or inside a CE
 * connectedCallback. The Svelte context glue (`TOOL_POLICY_ENGINE_KEY`)
 * lives in `engine-context.ts`.
 *
 * PR 1 ships the engine *without callers*. PR 2 wires it into
 * `ToolkitCoordinator`. PR 3 switches `<pie-item-toolbar>` over.
 */

import type {
	AssessmentEntity,
	AssessmentItemRef,
} from "@pie-players/pie-players-shared/types";

import type {
	CanonicalToolsConfig,
	ToolPlacementLevel,
} from "../../services/tools-config-normalizer.js";
import { normalizeToolsConfig } from "../../services/tools-config-normalizer.js";
import type { ToolRegistry } from "../../services/ToolRegistry.js";

import type {
	ToolPolicyDecision,
	ToolPolicyDecisionRequest,
} from "./decision-types.js";
import type { PolicySource } from "./PolicySource.js";
import { composeDecision } from "./compose-decision.js";
import { QtiPolicySource } from "../sources/QtiPolicySource.js";

export type QtiEnforcementMode = "on" | "off";

export interface ToolPolicyEngineInputs {
	tools?: CanonicalToolsConfig | null;
	assessment?: AssessmentEntity | null;
	currentItemRef?: AssessmentItemRef | null;
	/**
	 * "on" applies the QTI 6-level precedence (default — see M8
	 * design Q5). Hosts that explicitly want to bypass QTI gates
	 * (test fixtures, demos that don't carry an `AssessmentEntity`)
	 * pass `"off"`.
	 */
	qtiEnforcement?: QtiEnforcementMode;
}

export interface ToolPolicyEngineArgs {
	toolRegistry: ToolRegistry;
	inputs?: ToolPolicyEngineInputs;
	customSources?: readonly PolicySource[];
	/** Stable context label used in provenance trails. Defaults to "tool-policy". */
	contextId?: string;
}

export interface ToolPolicyChangeEvent {
	/** What changed in this update. */
	reason:
		| "inputs"
		| "policy-source-added"
		| "policy-source-removed"
		| "qti-enforcement"
		| "disposed";
	/** Snapshot of the engine's inputs after the change. */
	inputs: Readonly<ResolvedEngineInputs>;
}

export interface ResolvedEngineInputs {
	tools: CanonicalToolsConfig;
	assessment: AssessmentEntity | null;
	currentItemRef: AssessmentItemRef | null;
	qtiEnforcement: QtiEnforcementMode;
}

export type ToolPolicyChangeListener = (event: ToolPolicyChangeEvent) => void;

const DEFAULT_TOOLS: CanonicalToolsConfig = normalizeToolsConfig({
	policy: { allowed: [], blocked: [] },
	placement: { section: [], item: [], passage: [] },
	providers: {},
});

export class ToolPolicyEngine {
	private readonly toolRegistry: ToolRegistry;
	private readonly contextId: string;
	private readonly qtiSource: QtiPolicySource;
	private readonly customSources: PolicySource[];
	private readonly listeners = new Set<ToolPolicyChangeListener>();

	private tools: CanonicalToolsConfig;
	private assessment: AssessmentEntity | null;
	private currentItemRef: AssessmentItemRef | null;
	private qtiEnforcement: QtiEnforcementMode;
	private disposed = false;

	constructor(args: ToolPolicyEngineArgs) {
		this.toolRegistry = args.toolRegistry;
		this.contextId = args.contextId ?? "tool-policy";
		this.qtiSource = new QtiPolicySource(this.toolRegistry);
		this.customSources = args.customSources ? [...args.customSources] : [];

		const inputs = args.inputs ?? {};
		this.tools = inputs.tools ?? DEFAULT_TOOLS;
		this.assessment = inputs.assessment ?? null;
		this.currentItemRef = inputs.currentItemRef ?? null;
		this.qtiEnforcement = inputs.qtiEnforcement ?? "on";
	}

	/**
	 * Resolve the visible tool set for a given placement level and
	 * scope.
	 *
	 * `visibleTools` and `diagnostics` are deterministic with respect
	 * to the engine's currently-bound inputs — calling `decide(...)`
	 * twice with identical inputs returns structurally equal
	 * `visibleTools` and `diagnostics`. The returned `provenance`
	 * carries call-time `evaluatedAt` timestamps generated by
	 * `ToolPolicyProvenanceBuilder` (one per `decide(...)`); two
	 * back-to-back calls therefore produce different `evaluatedAt`
	 * values even though the policy decision itself is identical.
	 * Hosts that want timestamp-stable provenance should reuse a
	 * cached `ToolPolicyDecision` rather than re-call `decide(...)`.
	 */
	decide(request: ToolPolicyDecisionRequest): ToolPolicyDecision {
		this.assertNotDisposed();
		const requestContextId = request.scope.scopeId
			? `${this.contextId}:${request.level}:${request.scope.scopeId}`
			: `${this.contextId}:${request.level}`;
		return composeDecision({
			request,
			tools: this.tools,
			qti: {
				source: this.qtiSource,
				assessment: this.assessment ?? undefined,
				currentItemRef: this.currentItemRef ?? undefined,
				enforcement: this.qtiEnforcement,
			},
			customSources: this.customSources,
			contextId: requestContextId,
		});
	}

	/**
	 * Convenience wrapper for hosts that just want the visible tool
	 * IDs. Equivalent to `decide(...).visibleTools.map(e => e.toolId)`.
	 */
	getVisibleToolIds(level: ToolPlacementLevel, scopeId: string): string[] {
		return this.decide({
			level,
			scope: { level, scopeId },
		}).visibleTools.map((entry) => entry.toolId);
	}

	/**
	 * Apply a partial input update.
	 *
	 * Each key is value-diffed via `Object.is` before storing, so callers
	 * may safely re-push the same reference (e.g. on Svelte effect
	 * re-runs caused by unrelated tracked reads): no-op patches do not
	 * fire `onPolicyChange` listeners. This contract is relied on by
	 * `PieAssessmentToolkit.svelte`'s prop-forwarding effect and by the
	 * coordinator's `getFloatingTools()` / `decideToolPolicy()` lockstep
	 * tests.
	 *
	 * `qtiEnforcement` is stored on its own field and always emits with
	 * a distinct `"qti-enforcement"` reason when no other key changed,
	 * so PR 4's auto-on flip can target that reason without a separate
	 * event channel.
	 */
	updateInputs(patch: Partial<ToolPolicyEngineInputs>): void {
		this.assertNotDisposed();
		let changed = false;
		let qtiChanged = false;
		if ("tools" in patch) {
			const next = patch.tools ?? DEFAULT_TOOLS;
			if (!Object.is(this.tools, next)) {
				this.tools = next;
				changed = true;
			}
		}
		if ("assessment" in patch) {
			const next = patch.assessment ?? null;
			if (!Object.is(this.assessment, next)) {
				this.assessment = next;
				changed = true;
			}
		}
		if ("currentItemRef" in patch) {
			const next = patch.currentItemRef ?? null;
			if (!Object.is(this.currentItemRef, next)) {
				this.currentItemRef = next;
				changed = true;
			}
		}
		if ("qtiEnforcement" in patch && patch.qtiEnforcement) {
			if (this.qtiEnforcement !== patch.qtiEnforcement) {
				this.qtiEnforcement = patch.qtiEnforcement;
				qtiChanged = true;
			}
		}
		if (changed || qtiChanged) {
			this.emit({
				reason: qtiChanged && !changed ? "qti-enforcement" : "inputs",
				inputs: this.snapshotInputs(),
			});
		}
	}

	registerPolicySource(source: PolicySource): () => void {
		this.assertNotDisposed();
		this.customSources.push(source);
		this.emit({
			reason: "policy-source-added",
			inputs: this.snapshotInputs(),
		});
		return () => {
			const idx = this.customSources.indexOf(source);
			if (idx !== -1) {
				this.customSources.splice(idx, 1);
				if (!this.disposed) {
					this.emit({
						reason: "policy-source-removed",
						inputs: this.snapshotInputs(),
					});
				}
			}
		};
	}

	onPolicyChange(listener: ToolPolicyChangeListener): () => void {
		this.listeners.add(listener);
		return () => {
			this.listeners.delete(listener);
		};
	}

	getInputs(): Readonly<ResolvedEngineInputs> {
		return this.snapshotInputs();
	}

	dispose(): void {
		if (this.disposed) return;
		this.disposed = true;
		this.emit({
			reason: "disposed",
			inputs: this.snapshotInputs(),
		});
		this.listeners.clear();
		this.customSources.length = 0;
	}

	private snapshotInputs(): Readonly<ResolvedEngineInputs> {
		return Object.freeze({
			tools: this.tools,
			assessment: this.assessment,
			currentItemRef: this.currentItemRef,
			qtiEnforcement: this.qtiEnforcement,
		});
	}

	private emit(event: ToolPolicyChangeEvent): void {
		for (const listener of Array.from(this.listeners)) {
			try {
				listener(event);
			} catch {
				// Subscriber errors must not break the engine. Hosts that
				// want error telemetry should wrap their listener.
			}
		}
	}

	private assertNotDisposed(): void {
		if (this.disposed) {
			throw new Error("ToolPolicyEngine has been disposed.");
		}
	}
}
